# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
# Starter pipeline


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'  
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: "$(AZURE_RM_SVC_CONNECTION)"
    action: "Create Or Update Resource Group"
    resourceGroupName: "$(RESOURCE_GROUP)"
    location: $(LOCATION)
    templateLocation: "Linked artifact"
    deploymentMode: "Incremental"
  displayName: "Deploy MLOps resources to Azure"

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
